# These are supported funding model platforms

github: [@codracademy](https://github.com/codracademy)
community_bridge: [CODR Academy](https://chat.whatsapp.com/E3wdmctRbRX6CadaylO80f)
buy_me_a_coffee:  Gpay : 8017874821 
